#!/usr/bin/env python3

"""
    03_run_declare_conformance.py
    ===============================
    This script performs Declare conformance checking on a given event log and Declare model.
    It follows these steps:
        1. Load event log from CSV.
        2. Convert to PM4Py EventLog.
        3. Export to XES format.
        4. Run Declare conformance checking using Declare4Py.
        5. Add CaseID to conformance results and save to CSV.
        6. Compute and save compliance statistics.
"""

from __future__ import annotations

from pathlib import Path
import pandas as pd

from pm4py.objects.log.exporter.xes import exporter as xes_exporter
from pm4py.objects.conversion.log import converter as log_converter

from Declare4Py.D4PyEventLog import D4PyEventLog
from Declare4Py.ProcessModels.DeclareModel import DeclareModel
from Declare4Py.ProcessMiningTasks.ConformanceChecking.MPDeclareAnalyzer import MPDeclareAnalyzer


# ===============================
# CONFIG
# ===============================

CSV_SEP = ";"
PRECISION = 2

CSV_PATH = Path("event_log/curia_log_en.csv")
XES_PATH = Path("event_log/curia_log_en.xes")
DECLARE_MODEL_PATH = Path("declare_model/curia_model.decl")

CONFORMANCE_DIR = Path("conformance_results")
CONFORMANCE_CSV = CONFORMANCE_DIR / "conformance_results.csv"

CASE_COL = "CaseID"
ACTIVITY_COL = "Activity"
TIMESTAMP_COL = "Timestamp"


# ===============================
# FUNCTIONS
# ===============================

def clean_constraint_headers(df: pd.DataFrame) -> pd.DataFrame:
    """
    Clean conformance matrix column headers generated by Declare4Py.

    Declare4Py may append trailing placeholders such as `| | |` to constraint
    names. This function removes that suffix and keeps the readable constraint
    label only.

    Args:
        df: Compliance DataFrame with constraint columns.

    Returns:
        A copy of the DataFrame with normalized column names.
    """
    df = df.copy()
    df.columns = [str(c).split("|", 1)[0].strip() for c in df.columns]
    return df

def extract_case_ids_from_pm4py_event_log(event_log) -> list[str]:
    """
    Extract case identifiers in trace order from a PM4Py EventLog.

    The returned ordering is intended to align trace-wise metrics produced by
    Declare4Py back to original case IDs.

    Args:
        event_log: PM4Py EventLog instance.

    Returns:
        List of case IDs as strings, one per trace, in event-log order.
    """
    case_ids: list[str] = []
    for trace in event_log:
        attrs = getattr(trace, "attributes", {}) or {}
        cid = attrs.get("concept:name")
        case_ids.append(str(cid))
    return case_ids


def compute_and_save_compliance_statistics(
    df_compliance: pd.DataFrame,
    output_dir: str | Path,
    case_id_col: str | None = "CaseID",
    violation_value: int = 1,
    top_n: int = 50,
    precision: int = PRECISION,
) -> dict[str, pd.DataFrame]:
    """
    Compute rule-level and case-level compliance statistics and save them to CSV.

    Parameters
    ----------
    df_compliance:
        Conformance matrix (rows = cases, columns = rules, values = 0/1).
        Assumes 1 = violation and 0 = compliant.
    output_dir:
        Directory where CSV files will be saved.
    case_id_col:
        Optional column name containing case IDs. If provided, it will be set as index.
    violation_value:
        Value representing a violation (default = 1).
    top_n:
        Number of worst cases to export separately.
    precision:
        Float rounding precision.

    Returns
    -------
    dict[str, pd.DataFrame]
        Dictionary with the generated summary tables:
        `rule_stats`, `case_stats`, `violations_distribution`, `summary`.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    df = df_compliance.copy()
    df.columns = df.columns.str.strip()

    if case_id_col and case_id_col in df.columns:
        df[case_id_col] = df[case_id_col].astype(str).str.strip()
        df = df.set_index(case_id_col)

    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df_constraints = df.dropna(axis=1, how="all").fillna(0).astype(int)

    # 1) Rule-level statistics
    rule_violation_rate = (df_constraints == violation_value).mean()
    rule_compliance_rate = 1.0 - rule_violation_rate

    rule_stats = pd.DataFrame(
        {
            "num_cases": len(df_constraints),
            "num_violations": (df_constraints == violation_value).sum(),
            "num_compliant": len(df_constraints) - (df_constraints == violation_value).sum(),
            "violation_rate": rule_violation_rate,
            "compliance_rate": rule_compliance_rate,
        }
    ).sort_values("violation_rate", ascending=False)

    float_cols = rule_stats.select_dtypes(include=["float", "float32", "float64"]).columns
    rule_stats[float_cols] = rule_stats[float_cols].round(precision)
    rule_stats.to_csv(output_dir / "rule_level_stats.csv", sep=CSV_SEP)

    # 2) Case-level statistics
    case_num_rules = df_constraints.shape[1]
    case_num_violations = (df_constraints == violation_value).sum(axis=1)
    case_compliance_score = 1.0 - (case_num_violations / case_num_rules) if case_num_rules > 0 else 1.0

    case_stats = pd.DataFrame(
        {
            "num_rules": case_num_rules,
            "num_violations": case_num_violations,
            "compliance_score": case_compliance_score,
        }
    ).sort_values("num_violations", ascending=False)

    float_cols = case_stats.select_dtypes(include=["float", "float32", "float64"]).columns
    case_stats[float_cols] = case_stats[float_cols].round(precision)
    case_stats.to_csv(output_dir / "case_level_stats.csv", sep=CSV_SEP)

    # 3) Top-N worst cases
    case_stats.head(top_n).to_csv(output_dir / f"top_{top_n}_worst_cases.csv", sep=CSV_SEP)

    # 4) Distribution of violations
    violations_distribution = (
        case_num_violations.value_counts()
        .sort_index()
        .rename_axis("num_violations")
        .reset_index(name="num_cases")
    )
    violations_distribution["pct_cases"] = violations_distribution["num_cases"] / len(df_constraints)
    float_cols = violations_distribution.select_dtypes(include=["float", "float32", "float64"]).columns
    violations_distribution[float_cols] = violations_distribution[float_cols].round(precision)
    violations_distribution.to_csv(output_dir / "violations_distribution.csv", sep=CSV_SEP, index=False)

    # 5) Violating cases per rule
    per_rule_dir = output_dir / "violating_cases_by_rule"
    per_rule_dir.mkdir(exist_ok=True)

    for rule_col in df_constraints.columns:
        viol_mask = df_constraints[rule_col] == violation_value
        viol_cases = case_stats.loc[viol_mask]
        viol_cases.to_csv(per_rule_dir / f"{rule_col}.csv", sep=CSV_SEP)

    # 6) Global summary
    summary = pd.DataFrame(
        [
            {
                "num_cases": len(df_constraints),
                "num_rules": case_num_rules,
                "overall_violation_rate_mean": float(rule_violation_rate.mean()) if case_num_rules > 0 else 0.0,
                "overall_compliance_rate_mean": float(rule_compliance_rate.mean()) if case_num_rules > 0 else 1.0,
                "avg_violations_per_case": float(case_num_violations.mean()) if len(df_constraints) else 0.0,
                "median_violations_per_case": float(case_num_violations.median()) if len(df_constraints) else 0.0,
                "min_compliance_score": float(case_stats["compliance_score"].min()) if len(case_stats) else 1.0,
                "median_compliance_score": float(case_stats["compliance_score"].median()) if len(case_stats) else 1.0,
                "max_compliance_score": float(case_stats["compliance_score"].max()) if len(case_stats) else 1.0,
            }
        ]
    )
    float_cols = summary.select_dtypes(include=["float", "float32", "float64"]).columns
    summary[float_cols] = summary[float_cols].round(precision)
    summary.to_csv(output_dir / "_summary.csv", sep=CSV_SEP, index=False)

    print(f"Compliance statistics saved in: {output_dir}")

    return {
        "rule_stats": rule_stats,
        "case_stats": case_stats,
        "violations_distribution": violations_distribution,
        "summary": summary,
    }


def ensure_declare_conditions(declare_model: DeclareModel) -> None:
    """
    Declare4Py 2.x expects explicit condition slots in each constraint.
    If missing in .decl, fill with empty strings to avoid runtime errors.

    Args:
        declare_model: Parsed Declare model to normalize before conformance.
    """
    for constraint in declare_model.constraints:
        conditions = list(constraint.get("condition", []))
        if constraint["template"].is_binary:
            while len(conditions) < 3:
                conditions.append("")
        else:
            while len(conditions) < 2:
                conditions.append("")
        constraint["condition"] = conditions

    declare_model.serialized_constraints = []
    declare_model.set_constraints()


# ===============================
# MAIN
# ===============================

def main() -> None:
    """
    Run the end-to-end Declare conformance workflow.

    Pipeline steps:
    1. Read and normalize the CSV event log.
    2. Convert to PM4Py EventLog and export to XES.
    3. Load Declare model and run conformance checking.
    4. Align conformance rows with CaseID and save matrix.
    5. Compute and persist compliance statistics.
    """
    CONFORMANCE_DIR.mkdir(parents=True, exist_ok=True)
    XES_PATH.parent.mkdir(parents=True, exist_ok=True)

    # -------------------------------
    # STEP 1 — Load CSV
    # -------------------------------
    print("Loading CSV log...")
    df = pd.read_csv(CSV_PATH, sep=CSV_SEP, encoding="utf-8")
    df.columns = df.columns.str.strip()

    # Convert timestamp
    df[TIMESTAMP_COL] = pd.to_datetime(df[TIMESTAMP_COL], errors="raise")

    # Rename to PM4Py standard
    df = df.rename(
        columns={
            CASE_COL: "case:concept:name",
            ACTIVITY_COL: "concept:name",
            TIMESTAMP_COL: "time:timestamp",
        }
    )

    # Sort
    df = df.sort_values(["case:concept:name", "time:timestamp", "concept:name"], kind="mergesort")

    # -------------------------------
    # STEP 2 — Convert to PM4Py EventLog
    # -------------------------------
    print("Converting to PM4Py EventLog...")
    parameters = {
        log_converter.Variants.TO_EVENT_LOG.value.Parameters.CASE_ID_KEY: "case:concept:name"
    }
    event_log = log_converter.apply(df, parameters=parameters, variant=log_converter.Variants.TO_EVENT_LOG)

    # IMPORTANT: capture CaseIDs in trace order (will be used to align conformance rows)
    case_ids = extract_case_ids_from_pm4py_event_log(event_log)

    # -------------------------------
    # STEP 3 — Export to XES
    # -------------------------------
    print("Exporting to XES...")
    xes_exporter.apply(event_log, str(XES_PATH))

    # -------------------------------
    # STEP 4 — Declare4Py Conformance
    # -------------------------------
    print("Running Declare conformance checking...")

    d4py_log = D4PyEventLog()
    d4py_log.parse_xes_log(str(XES_PATH))

    declare_model = DeclareModel().parse_from_file(str(DECLARE_MODEL_PATH))
    ensure_declare_conditions(declare_model)

    analyzer = MPDeclareAnalyzer(d4py_log, declare_model, consider_vacuity=False)
    conformance_results = analyzer.run()

    df_compliance = conformance_results.get_metric("state")
    if not isinstance(df_compliance, pd.DataFrame):
        df_compliance = pd.DataFrame(df_compliance)

    # -------------------------------
    # STEP 5 — Add CaseID + Save
    # -------------------------------
    if len(df_compliance) != len(case_ids):
        raise ValueError(
            f"Row mismatch: conformance has {len(df_compliance)} rows, "
            f"but the log has {len(case_ids)} traces. Cannot safely align CaseID."
        )

    df_compliance = df_compliance.copy()

    df_compliance = clean_constraint_headers(df_compliance)

    df_compliance.insert(0, "CaseID", case_ids)

    df_compliance.to_csv(CONFORMANCE_CSV, index=False, sep=CSV_SEP)
    print(f"Conformance results saved to: {CONFORMANCE_CSV}")

    # -------------------------------
    # STEP 6 — Statistics
    # -------------------------------
    compute_and_save_compliance_statistics(
        df_compliance=df_compliance,
        output_dir=CONFORMANCE_DIR,
        case_id_col="CaseID",
        precision=PRECISION,
    )

    print("\nFinished.")


if __name__ == "__main__":
    main()